### ISSUE TITLE
期货不能回测，是某个文件没有？

### ISSUE THREAD

**Issue by Xiams1921** [leewi9/fudan_soe_quant_issues#2]
代码：sp.GeneratePerformance('future', df['position'].values, savePerformance=True)

报错：

start generating performance ...
start loading S_DQ_ADJCLOSE, db_type is:h5, pleae wait ...
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-24-172dded761bb> in <module>
----> 1 sp.GeneratePerformance('future', df['position'], savePerformance=True)

/data/home/BTP_Wasabi/PlatformFolder/RootStrategyPlatform.py in GeneratePerformance(self, category, alpha, db_type, bookList, longShort, platLimit, tradingLimit, ipoLimit, showDailyPnl, savePerformance)
   1003 
   1004         #
-> 1005         cps_F = self.LoadData(category, 'S_DQ_ADJCLOSE', db_type=db_type)
   1006 
   1007         # vwap_F = self.LoadData('vwap_F', db_type=db_type)  # todo

/data/home/BTP_Wasabi/PlatformFolder/RootStrategyPlatform.py in LoadData(self, category, factor, db_type, fake_last_line, needDefaultData, format_type)
    814         #
    815         if db_type == 'h5':
--> 816             rst = self._get_records_from_hdf5(category, factor, format_type, fake_last_line=fake_last_line)
    817             return rst
    818         elif db_type == 'sqlite':

/data/home/BTP_Wasabi/PlatformFolder/RootStrategyPlatform.py in _get_records_from_hdf5(self, category, factor, format_type, fake_last_line)
    827         p = os.path.join(factor_hdf5_folder_path, factor)
    828         if not os.path.exists(p):
--> 829             raise Exception(p + ' not existed! please check ...')
    830         #
    831         hdf5_obj = self.generate_hdf5_obj_by_factor(factor, new_hdf5_folder_path=factor_hdf5_folder_path)

Exception: /data/home/BTP_Wasabi/Database/HDF5_191016/future/S_DQ_ADJCLOSE not existed! please check ...

**Comment by leewi9** [comment]
S_DQ_ADJCLOSE 是 ashare 也就是A股的因子名称

期货的名称不是这个，具体在demo中有相关说明

**Comment by leewi9** [comment]
另外，期货的 performance 不同于 A股，GeneratePerformance 是 A股专用的

**Comment by leiyang99** [comment]
期货回测比较简单，可以自己写一个回测函数。后期我们补上参考的回测函数
