### ISSUE TITLE
股票的回测函数有概率报错，图也一直载不出，有时候还会出NaN

### ISSUE THREAD

**Issue by Xiams1921** [leewi9/fudan_soe_quant_issues#4]
start loading S_DQ_CLOSE, db_type is:h5, please wait ...
start loading S_DQ_ADJCLOSE, db_type is:h5, please wait ...
start loading S_DQ_LOW, db_type is:h5, please wait ...
start loading S_DQ_HIGH, db_type is:h5, please wait ...
start loading S_DQ_ADJOPEN, db_type is:h5, please wait ...
start loading S_DQ_TRADESTATUS_SIG, db_type is:h5, please wait ...
start loading S_DQ_ADJPRECLOSE, db_type is:h5, please wait ...
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-12-da5f47fa40fa> in <module>
----> 1 sp.GeneratePerformanceAshare(alpha,limit_days=90,cost=0.0008,cash_init=1000*10000,benchmark="SZZZ",mode=0)

/data/BTP_Wasabi/PlatformFolder/RootStrategyPlatform.py in GeneratePerformanceAshare(self, alpha, limit_days, cost, cash_init, benchmark, mode)
   1170             temp_max_value = max(temp_max_value, deri.iloc[j - 1, 0])
   1171             if (max_draw_down > deri.iloc[j, 0] / temp_max_value - 1):
-> 1172                 md_deri_start_date = md_tem_start_date
   1173                 md_deri_end_date = deri.index[j][0]
   1174             max_draw_down = min(max_draw_down, deri.iloc[j, 0] / temp_max_value - 1)

UnboundLocalError: local variable 'md_tem_start_date' referenced before assignment

**Comment by leiyang99** [comment]
回测日期设定的截至日期最晚是当天减去两个交易日。图像加载不出来，请先用360安全浏览器。如还有问题加我微信17521047274

**Comment by leiyang99** [comment]
感谢提问，bug已经修复，回测函数的图也可以正常显示了。请重新测试。
