### ISSUE TITLE
[error] AttributeError: 'StrategyPlatform' object has no attribute 'btp'

### ISSUE THREAD

**Issue by itaowei** [leewi9/fudan_soe_quant_issues#6]
之前这个代码还可以运行的
现在咋报错信息这个啦/捂脸.jpg

**Comment by leewi9** [comment]
代码有升级，可以参考下最新的demo

**Comment by itaowei** [comment]
可是新的demo没有btp这个属性 请问我应该应该怎么弄才能读日期

**Comment by itaowei** [comment]
![4135920B-53C5-4582-B6DD-4A1DCF379C68](https://user-images.githubusercontent.com/19475586/69490119-26750600-0ebe-11ea-9727-a9af06099ce2.jpeg)
如上图

**Comment by leewi9** [comment]
试下 sp.GetTradeDateList()
