### ISSUE TITLE
许多财务因子不可用

### ISSUE THREAD

**Issue by AAhab** [leewi9/fudan_soe_quant_issues#8]
许多财务因子如YOY_TR、YOY_OR、YOYOP等显示不可用

**Comment by leewi9** [comment]
AShareFinancialIndicator 加前缀 ASFI_
AShareCashFlow 加前缀 ASCF_
AShareIncome 加前缀 ASI_

**Comment by AAhab** [comment]
老师，仍存在部分因子使用不了
如销售毛利率ASFI_GROSSPROFITMARGIN 
![image](https://user-images.githubusercontent.com/20652304/70768070-99c3b680-1d9e-11ea-8a86-cf0180bf5432.png)

**Comment by leewi9** [comment]
是不是应该是 ASFI_S_FA_GROSSPROFITMARGIN 或 ASFI_S_QFA_GROSSPROFITMARGIN

**Comment by AAhab** [comment]
已解决！谢谢老师
